// Data awal in-memory ("database" klien). Lihat docs/PRD.md §12.
import type { IdentityField, Question, Scale, Survey } from "@/types";

// ---- §12.4 Scales ----
export const seedScales: Scale[] = [
  {
    id: "scl_puas4",
    nama: "Skala puas (4 poin)",
    tipe: "KEPUASAN",
    poin: 4,
    labels: ["Sangat tidak puas", "Tidak puas", "Puas", "Sangat puas"],
  },
  {
    id: "scl_setuju4",
    nama: "Skala setuju (4 poin)",
    tipe: "PERSETUJUAN",
    poin: 4,
    labels: ["Sangat tidak setuju", "Tidak setuju", "Setuju", "Sangat setuju"],
  },
  {
    id: "scl_nps",
    nama: "NPS (0-10)",
    tipe: "NPS",
    poin: 11,
    labels: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    endpointKiri: "Sangat Tidak Mungkin",
    endpointKanan: "Sangat Mungkin",
  },
];

// ---- §12.1 Surveys ----
export const seedSurveys: Survey[] = [
  {
    id: "srv_01",
    kode: "SKP-2026",
    nama: "Survei Kepuasan Pelanggan Domestik 2026",
    jenisNota: "Domestik",
    periode: 2026,
    status: "draft",
    tanggalMulai: "2026-07-01",
    tanggalSelesai: "2026-09-30",
    deskripsi: "Survei kepuasan pelanggan domestik tahun 2026.",
    jumlahPertanyaan: 14,
    jumlahResponden: 0,
    terakhirDiubah: "2026-06-18T09:30:00",
    createdAt: "2026-06-01T08:00:00",
  },
  {
    id: "srv_02",
    kode: "SKP-2025",
    nama: "Survei Penumpang Internasional Q3",
    jenisNota: "Internasional",
    periode: 2025,
    status: "aktif",
    tanggalMulai: "2025-07-01",
    tanggalSelesai: "2025-09-30",
    jumlahPertanyaan: 22,
    jumlahResponden: 1248,
    terakhirDiubah: "2026-06-12T14:05:00",
    createdAt: "2025-06-10T08:00:00",
  },
  {
    id: "srv_03",
    kode: "SKP-2024",
    nama: "Survei Layanan SPSL Group - Phase 1",
    jenisNota: "SPSL Group",
    periode: 2024,
    status: "selesai",
    tanggalMulai: "2024-04-01",
    tanggalSelesai: "2024-06-30",
    jumlahPertanyaan: 20,
    jumlahResponden: 3910,
    terakhirDiubah: "2024-12-31T16:00:00",
    createdAt: "2024-03-01T08:00:00",
  },
  {
    id: "srv_04",
    kode: "SKP-2023",
    nama: "Evaluasi Tahunan Domestik 2023",
    jenisNota: "Domestik",
    periode: 2023,
    status: "arsip",
    tanggalMulai: "2023-07-01",
    tanggalSelesai: "2023-09-30",
    jumlahPertanyaan: 20,
    jumlahResponden: 0,
    terakhirDiubah: "2023-12-20T08:00:00",
    createdAt: "2023-06-01T08:00:00",
  },
];

// ---- §12.2 Questions (hanya SKP-2026 / srv_01 yang punya tree lengkap) ----
export const seedQuestions: Question[] = [
  // C1 — GRUP (5 anak)
  {
    id: "q_c1",
    surveyId: "srv_01",
    kode: "C1",
    parentId: null,
    teks: "Fasilitas & dimensi layanan",
    tipe: "GRUP",
    urutan: 1,
    wajibDiisi: false,
    isGroup: true,
    childCount: 5,
  },
  {
    id: "q_c1_1",
    surveyId: "srv_01",
    kode: "C1.1",
    parentId: "q_c1",
    teks: "Kebersihan & kenyamanan fasilitas terminal",
    tipe: "SKALA_KEPUASAN",
    urutan: 1,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_puas4",
  },
  {
    id: "q_c1_2",
    surveyId: "srv_01",
    kode: "C1.2",
    parentId: "q_c1",
    teks: "Ketersediaan & kejelasan informasi/papan petunjuk",
    tipe: "SKALA_KEPUASAN",
    urutan: 2,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_puas4",
  },
  {
    id: "q_c1_3",
    surveyId: "srv_01",
    kode: "C1.3",
    parentId: "q_c1",
    teks: "Kecepatan proses layanan bongkar muat",
    tipe: "SKALA_KEPUASAN",
    urutan: 3,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_puas4",
  },
  {
    id: "q_c1_4",
    surveyId: "srv_01",
    kode: "C1.4",
    parentId: "q_c1",
    teks: "Keramahan & profesionalisme petugas",
    tipe: "SKALA_KEPUASAN",
    urutan: 4,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_puas4",
  },
  {
    id: "q_c1_5",
    surveyId: "srv_01",
    kode: "C1.5",
    parentId: "q_c1",
    teks: "Keamanan barang & area pelabuhan",
    tipe: "SKALA_KEPUASAN",
    urutan: 5,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_puas4",
  },

  // C2 — NPS
  {
    id: "q_c2",
    surveyId: "srv_01",
    kode: "C2",
    parentId: null,
    teks: "Seberapa besar kemungkinan Anda merekomendasikan Pelindo?",
    tipe: "NPS",
    urutan: 2,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_nps",
  },

  // C3 — YA_TIDAK (+ 3 anak)
  {
    id: "q_c3",
    surveyId: "srv_01",
    kode: "C3",
    parentId: null,
    teks: "Apakah Anda menggunakan pelabuhan lain?",
    tipe: "YA_TIDAK",
    urutan: 3,
    wajibDiisi: true,
    isGroup: false,
  },
  {
    id: "q_c3_1",
    surveyId: "srv_01",
    kode: "C3.1",
    parentId: "q_c3",
    teks: "Sebutkan nama pelabuhan tersebut!",
    tipe: "TEKS",
    urutan: 1,
    wajibDiisi: false,
    isGroup: false,
    logic: {
      conditions: [
        { sourceQuestionKode: "C3", operator: "sama_dengan", value: "Ya" },
      ],
    },
  },
  {
    id: "q_c3_2",
    surveyId: "srv_01",
    kode: "C3.2",
    parentId: "q_c3",
    teks: "Tingkat kepuasan terhadap pelabuhan lain tersebut",
    tipe: "SKALA_KEPUASAN",
    urutan: 2,
    wajibDiisi: false,
    isGroup: false,
    scaleId: "scl_puas4",
  },
  {
    id: "q_c3_3",
    surveyId: "srv_01",
    kode: "C3.3",
    parentId: "q_c3",
    teks: "Siapa pengelola pelabuhan tersebut?",
    tipe: "PILIHAN_TUNGGAL",
    urutan: 3,
    wajibDiisi: false,
    isGroup: false,
    acakOpsi: false,
    options: [
      { id: "opt_c3_3_a", label: "BUMN", skor: 3, urutan: 1 },
      { id: "opt_c3_3_b", label: "Swasta nasional", skor: 2, urutan: 2 },
      { id: "opt_c3_3_c", label: "Operator asing", skor: 1, urutan: 3 },
    ],
  },

  // C4 — GRUP (2 anak)
  {
    id: "q_c4",
    surveyId: "srv_01",
    kode: "C4",
    parentId: null,
    teks: "Loyalitas pelanggan",
    tipe: "GRUP",
    urutan: 4,
    wajibDiisi: false,
    isGroup: true,
    childCount: 2,
  },
  {
    id: "q_c4_1",
    surveyId: "srv_01",
    kode: "C4.1",
    parentId: "q_c4",
    teks: "Saya akan kembali menggunakan layanan Pelindo",
    tipe: "SKALA_PERSETUJUAN",
    urutan: 1,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_setuju4",
  },
  {
    id: "q_c4_2",
    surveyId: "srv_01",
    kode: "C4.2",
    parentId: "q_c4",
    teks: "Saya bersedia merekomendasikan ke mitra bisnis",
    tipe: "SKALA_PERSETUJUAN",
    urutan: 2,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_setuju4",
  },

  // C5 — SKALA_KEPUASAN
  {
    id: "q_c5",
    surveyId: "srv_01",
    kode: "C5",
    parentId: null,
    teks: "Penerapan SMAP ISO 37001 di lingkungan pelabuhan",
    tipe: "SKALA_KEPUASAN",
    urutan: 5,
    wajibDiisi: true,
    isGroup: false,
    scaleId: "scl_puas4",
  },

  // C7 — PILIHAN_GANDA
  {
    id: "q_c7",
    surveyId: "srv_01",
    kode: "C7",
    parentId: null,
    teks: "Kendala/pain points yang Anda rasakan (boleh lebih dari satu)",
    tipe: "PILIHAN_GANDA",
    urutan: 6,
    wajibDiisi: false,
    isGroup: false,
    options: [
      { id: "opt_c7_a", label: "Waktu tunggu layanan lama", urutan: 1 },
      { id: "opt_c7_b", label: "Biaya layanan tinggi", urutan: 2 },
      { id: "opt_c7_c", label: "Informasi kurang jelas", urutan: 3 },
      { id: "opt_c7_d", label: "Fasilitas terbatas", urutan: 4 },
    ],
  },
];

// ---- §12.3 Identity fields (grup "Identitas", untuk srv_01) ----
const identitySpec: Array<
  Pick<IdentityField, "nama" | "sumber" | "deskripsi">
> = [
  {
    nama: "No Billing",
    sumber: "OTOMATIS",
    deskripsi: "Lookup dari database Pelindo",
  },
  {
    nama: "Nama Cabang",
    sumber: "OTOMATIS",
    deskripsi: "Lookup dari database Pelindo",
  },
  {
    nama: "Nama Entitas Bisnis Pelindo",
    sumber: "OTOMATIS",
    deskripsi: "Lookup dari database Pelindo",
  },
  {
    nama: "Nama Responden",
    sumber: "ISIAN",
    deskripsi: "Diisi oleh Responden",
  },
  {
    nama: "Nomor WA/Handphone",
    sumber: "ISIAN",
    deskripsi: "Diisi oleh Responden",
  },
  {
    nama: "Nama Perusahaan / Nama Kapal",
    sumber: "OTOMATIS",
    deskripsi: "Lookup dari database Pelindo",
  },
  {
    nama: "Jenis Pelayanan Paling Dominan",
    sumber: "PILIHAN",
    deskripsi: "Lookup dari database Pelindo",
  },
  { nama: "Kategori Responden", sumber: "PILIHAN", deskripsi: "Lookup" },
  {
    nama: "Tanggal Pengisian",
    sumber: "SISTEM",
    deskripsi: "Diisi otomatis sistem",
  },
  {
    nama: "Nama Enumerator",
    sumber: "OTOMATIS",
    deskripsi: "Lookup dari database Pelindo",
  },
];

export const seedIdentityFields: IdentityField[] = identitySpec.map((f, i) => ({
  id: `idf_${String(i + 1).padStart(2, "0")}`,
  surveyId: "srv_01",
  urutan: i + 1,
  ...f,
}));
